general.import = [ "tokyo-night.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Medium" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 14

[window]
padding.x = 0
padding.y = 0
# decorations = "None"
opacity = 0.90

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
 { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

